BOX_IMAGE = "generic/ubuntu2204"
BOX_VERSION = "4.3.12"
MEMORY = "2048"
CPU = "2"
BRIDGE_INTERFACE = "Intel(R) Ethernet Controller (3) I225-V"
BOX_NAME = "file-server"

Vagrant.configure("2") do |config|
  config.vm.define BOX_NAME do |subconfig|
    subconfig.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", MEMORY, "--cpus", CPU]
    end
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.box_version = BOX_VERSION
    subconfig.vm.box_check_update = false
    # hostname and IP
    subconfig.vm.hostname = BOX_NAME
    subconfig.vm.network :public_network, adapter: 2, bridge: BRIDGE_INTERFACE, auto_config: false

  end
  # copy 01-netcfg.yaml to the VM from the host
  config.vm.provision "file", source: "./01-netcfg.yaml", destination: "/tmp/01-netcfg.yaml"
  
  # run shell commands in the BOX
  config.vm.provision "shell", inline: <<-SHELL
    sudo echo "$IP $BOX_NAME" | sudo tee -a /etc/hosts
    sudo mv /tmp/01-netcfg.yaml /etc/netplan/01-netcfg.yaml
    sudo chmod 600 /etc/netplan/*.yaml
    sudo netplan apply
  SHELL
end
