BOX_IMAGE = "generic/ubuntu2204"
BOX_VERSION = "4.2.16"
MEMORY = "2048"
CPU = "1"
IP = "10.200.13.161"
SUBNETMASK = "255.255.248.0"
BRIDGE_INTERFACE = "Intel(R) 82578DM Gigabit Network Connection"
BOX_NAME = "file-server"

Vagrant.configure("2") do |config|
  config.vm.define BOX_NAME do |subconfig|
    subconfig.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", MEMORY, "--cpus", CPU]
    end
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.box_version = BOX_VERSION
    subconfig.vm.box_check_update = false
    # hostname and IP
    subconfig.vm.hostname = BOX_NAME
    subconfig.vm.network :public_network, ip: IP, netmask: SUBNETMASK, :device => "eth1", :adapter => 2, hostname: true, bridge: BRIDGE_INTERFACE
  end
  # run shell commands in the BOX
  config.vm.provision "shell", inline: <<-SHELL
    sudo echo "$IP $BOX_NAME" | sudo tee -a /etc/hosts
  SHELL
end
