BOX_IMAGE = "generic/ubuntu2204"
BOX_VERSION = "4.1.8"

Vagrant.configure("2") do |config|
  config.vm.define "dockervm" do |subconfig|

    subconfig.vm.provider :vmware_desktop do |v| 
      v.vmx["memsize"] = "4096"
    end
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.box_version = BOX_VERSION
    subconfig.vm.box_check_update  = false
    # hostname and IP
    subconfig.vm.hostname = "dockervm"
    subconfig.vm.network :public_network, ip: "192.168.1.157", :device => "eth1", :adapter => 2, hostname: true, bridge: "Qualcomm Atheros AR8151 PCI-E Gigabit Ethernet Controller (NDIS 6.30)"
    # subconfig.vm.network "public_network", ip: "192.168.245.173", :device => "eth2", :adapter => 3, :netmask => "255.255.255.0", bridge: "VMware Virtual Ethernet Adapter for VMnet1"
  end
  # run shell commands in the BOX
  config.vm.provision "shell", path: "install.sh", privileged: true
  config.vm.provision "shell", path: "post_install.sh", privileged: false
  # default route
  config.vm.provision "shell", path: "add_dg.sh", privileged: true, run: "always"
end