BOX_IMAGE = "generic/ubuntu2204"
BOX_VERSION = "4.2.16"
MEMORY = "4096"
CPU = "2"
IP = "192.168.1.165"
IP2 = "192.168.245.173"
BRIDGE_INTERFACE = "Intel(R) Ethernet Controller (3) I225-V"
BRIDGE_INTERFACE2 = "VMware Virtual Ethernet Adapter for VMnet1"
BOX_NAME = "dockervm"

Vagrant.configure("2") do |config|
  config.vm.define BOX_NAME do |subconfig|
    subconfig.vm.provider "vmware_desktop" do |v|
      v.vmx["memsize"] = "4096"
      v.vmx["numvcpus"] = "4"
    end
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.box_version = BOX_VERSION
    subconfig.vm.box_check_update = false
    # hostname and IP
    subconfig.vm.hostname = BOX_NAME
    subconfig.vm.network :public_network, ip: IP, :device => "eth1", :adapter => 2, hostname: true, bridge: BRIDGE_INTERFACE
    # subconfig.vm.network "public_network", ip: IP2, :device => "eth2", :adapter => 3, :netmask => "255.255.255.0", bridge: BRIDGE_INTERFACE2
  end
  # run shell commands in the BOX
  config.vm.provision "shell", path: "install.sh", privileged: true
  config.vm.provision "shell", path: "post_install.sh", privileged: false
  # default route
  config.vm.provision "shell", path: "add_dg.sh", privileged: true, run: "always"
end
