BOX_IMAGE = "generic/ubuntu2204"
BOX_VERSION = "4.3.12"
BOX_MEMORY = "4096"
CPU = "2"
IP = "192.168.1.165"
SUBNETMASK = "255.255.255.0"
BRIDGE_INTERFACE = "Intel(R) Ethernet Controller (3) I225-V"
BOX_NAME = "vscode-vmware"

Vagrant.configure("2") do |config|
  config.vm.define BOX_NAME do |subconfig|
    subconfig.vm.provider "vmware_desktop" do |v|
      v.gui = true
      v.vmx["memsize"] = BOX_MEMORY
      v.vmx["numvcpus"] = CPU
    end
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.box_version = BOX_VERSION
    subconfig.vm.box_check_update = false
    # hostname and IP
    subconfig.vm.hostname = BOX_NAME
    subconfig.vm.network :public_network, ip: IP, :device => "eth1", :adapter => 2, :netmask => SUBNETMASK, bridge: BRIDGE_INTERFACE, hostname: true
  end
  # run shell commands in the BOX
  config.vm.provision "shell", path: "install.sh", privileged: true
  config.vm.provision "shell", path: "post_install.sh", privileged: false
  # default route
  config.vm.provision "shell", path: "add_dg.sh", privileged: true, run: "always"
end
