BOX_IMAGE = "generic/rocky8"
BOX_VERSION = "4.2.16"
MEMORY = "4096"
CPU = "4"
# BRIDGE_INTERFACE = "Intel(R) Ethernet Controller (3) I225-V"
BRIDGE_INTERFACE = "Intel(R) Ethernet Connection (2) I219-LM"
IP = "10.200.13.200"
NETMASK = "255.255.248.0"
DEFAULT_GATEWAY = "10.200.15.254"
BOX_NAME = "rocky8"

# Network configuration script
$network_script = <<-SCRIPT
  CONNECTION_NAME=$(nmcli -t -f NAME,DEVICE connection show --active | tail -n1 | cut -d':' -f1)
  sudo nmcli connection modify "$CONNECTION_NAME" ipv4.gateway #{DEFAULT_GATEWAY}
  sudo nmcli connection modify "$CONNECTION_NAME" ipv4.route-metric 10
  sudo nmcli connection up "$CONNECTION_NAME"

SCRIPT

Vagrant.configure("2") do |config|
  config.vm.define BOX_NAME do |subconfig|
    subconfig.vm.provider :virtualbox do |v|
      # v.gui = true
      v.customize ["modifyvm", :id, "--memory", MEMORY, "--cpus", CPU]
    end

    # Box configuration
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.box_version = BOX_VERSION
    subconfig.vm.box_check_update = false
    subconfig.vm.hostname = BOX_NAME
    
    # Public network configuration
    subconfig.vm.network :public_network, ip: IP,:netmask => NETMASK, bridge: BRIDGE_INTERFACE

    # Run network configuration script
    subconfig.vm.provision "shell", run: "always", inline: $network_script
  end

  # Update /etc/hosts to map hostname to IP
  config.vm.provision "shell", inline: <<-SHELL
    echo "#{IP} #{BOX_NAME}" | sudo tee -a /etc/hosts
  SHELL
end
