BOX_IMAGE = "generic/rocky8"
BOX_VERSION = "4.2.16"
MEMORY = "4096"
CPU = "4"
IP = "192.168.1.154"
BRIDGE_INTERFACE = "Intel(R) Ethernet Controller (3) I225-V"
BOX_NAME = "rocky8"

Vagrant.configure("2") do |config|
  config.vm.define BOX_NAME do |subconfig|
    subconfig.vm.provider :virtualbox do |v|
      # v.gui = true
      v.customize ["modifyvm", :id, "--memory", MEMORY, "--cpus", CPU]
    end
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.box_version = BOX_VERSION
    subconfig.vm.box_check_update = false
    # hostname and IP
    subconfig.vm.hostname = BOX_NAME
    subconfig.vm.network :public_network, ip: IP, hostname: true, bridge: BRIDGE_INTERFACE
  end
  # run shell commands in the BOX
  config.vm.provision "shell", inline: <<-SHELL
  CONNECTION_NAME=$(nmcli -t -f NAME,DEVICE connection show --active | tail -n1 | cut -d':' -f1)

  echo "#{IP} #{BOX_NAME}" | sudo tee -a /etc/hosts
  
  sudo nmcli connection modify "$CONNECTION_NAME" ipv4.addresses #{IP}/24
  sudo nmcli connection modify "$CONNECTION_NAME" ipv4.gateway 192.168.1.254
  sudo nmcli connection modify "$CONNECTION_NAME" ipv4.route-metric 0
  sudo nmcli connection modify "$CONNECTION_NAME" ipv4.method manual
  sudo nmcli connection up "$CONNECTION_NAME"
SHELL
end
