BOX_IMAGE = "generic/ubuntu2204"
BOX_VERSION = "4.1.8"
BOX_MEMORY = "2048"
BOX_NAME = "ubuntu2204"

Vagrant.configure("2") do |config|
  config.vm.define BOX_NAME do |subconfig|

    subconfig.vm.provider :virtualbox do |v| 
      # v.gui = true
      v.customize ["modifyvm", :id, "--memory", BOX_MEMORY] 
    end
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.box_version = BOX_VERSION
    subconfig.vm.box_check_update  = false
    # hostname and IP
    subconfig.vm.hostname = BOX_NAME
    subconfig.vm.network :public_network, ip: "192.168.1.155", hostname: true, bridge: "Qualcomm Atheros AR8151 PCI-E Gigabit Ethernet Controller (NDIS 6.30)"
  end
  # run shell commands in the BOX
  config.vm.provision "shell", inline: <<-SHELL
    sudo echo "192.168.1.155 $BOX_NAME" | sudo tee -a /etc/hosts
  SHELL
end