Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_version = "4.3.12"
  config.vm.hostname = "k3s-rook-vm"

  # Add additional raw disks for ceph
  config.vm.disk :disk, name: "cephdisk", size: "10GB"

  config.vm.provider "vmware_workstation" do |vb|
    vb.memory = "8192" # Allocate sufficient memory
    vb.cpus = 4
    vb.gui = true
  end

  # Provisioning to install k3s
  config.vm.provision "shell", inline: <<-SHELL
    # Update package lists for Ubuntu 22.04
    sudo apt update

    # Install dependencies for k3s
    sudo apt install -y curl apt-transport-https ca-certificates

    # Install the k3s key
    curl -sfL https://get.k3s.io | sh -

    # Add vagrant user to the k3s group
    sudo usermod -aG vagrant $USER

    # Create the .kube directory
    mkdir -p /home/vagrant/.kube

    # Permission changes for k3s config
    sudo cp /etc/rancher/k3s/k3s.yaml /home/vagrant/.kube/config
    sudo chown vagrant:vagrant /home/vagrant/.kube/config

    # Set the KUBECONFIG environment variable
    export KUBECONFIG=/home/vagrant/.kube/config
    echo "export KUBECONFIG=/home/vagrant/.kube/config" >> .bashrc

    # Ensure disks are visible in the VM
    lsblk
  SHELL
end