BOX_IMAGE = "generic/ubuntu2004"
BOX_VERSION = "3.2.24"

Vagrant.configure("2") do |config|
  config.vm.define "dockervm" do |subconfig|

    subconfig.vm.provider :virtualbox do |v| 
      v.customize ["modifyvm", :id, "--memory", "4096"] 
    end
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.box_version = BOX_VERSION
    subconfig.vm.box_check_update  = false
    # hostname and IP
    subconfig.vm.hostname = "dockervm"
    subconfig.vm.network :public_network, ip: "192.168.1.155", hostname: true, bridge: "Qualcomm Atheros AR8151 PCI-E Gigabit Ethernet Controller (NDIS 6.30)"
  end
  # run shell commands in the BOX
  config.vm.provision "shell", path: "install.sh", privileged: true
  config.vm.provision "shell", path: "post_install.sh", privileged: false
end